version: 0.0
os: linux
# Place artifacts file inside EC2 instance
files:
  - source: /
    destination: /home/ubuntu/server/Webhooks
hooks:
  ApplicationStop:
    - location: /home/ubuntu/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/scripts/start_server.sh
      timeout: 300
      runas: ubuntu

